# minio-deployment.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
      annotations:
        logging: "enabled,format:json"
        fluentd.io/tag: minio.logs
        fluentd.io/address: fluent-bit.monitoring.svc.cluster.local:24224
        fluentd.io/async-connect: "true"
        fluentd.io/retry-wait: 1s
        fluentd.io/max-retries: "30"
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        args: ["server", "/data", "--console-address", ":9001"]
        env:
        - name: MINIO_ROOT_USER
          value: "minio"
        - name: MINIO_ROOT_PASSWORD
          value: "minio123"
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: "public"
        resources:
          limits:
            cpu: 250m
            memory: 400Mi
          requests:
            cpu: 102m
            memory: 180Mi
        ports:
        - containerPort: 9000
          name: http
        - containerPort: 9001
          name: console
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: database
  labels:
    app.kubernetes.io/name: minio
spec:
  selector:
    app.kubernetes.io/name: minio
  # type: LoadBalancer   # comment nodePort when enabled this
  type: NodePort
  ports:
    - name: http
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 30015