---
apiVersion: v1
kind: Secret
metadata:
  name: kibana-secret
  namespace: elastic-system
type: Opaque
stringData:
  ELASTICSEARCH_USERNAME: elastic
  ELASTICSEARCH_PASSWORD: c6O562qo2U73xMReW68mM3bM
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elastic-system
spec:
  selector:
    matchLabels:
      component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      serviceAccountName: kibana-sa
      containers:
      - name: kibana
        image: elastic/kibana:8.11.1
        imagePullPolicy: "IfNotPresent"
        env:
        # Use HTTPS URL for ECK-managed Elasticsearch
        - name: ELASTICSEARCH_HOSTS
          value: '["https://elastic-cluster-es-coordinating.elastic-system.svc.cluster.local:9200"]'
        - name: ELASTICSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
              name: kibana-secret
              key: ELASTICSEARCH_USERNAME
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kibana-secret
              key: ELASTICSEARCH_PASSWORD
        # SSL Configuration for connecting to ECK Elasticsearch
        - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
          value: "certificate"
        - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
          value: "/usr/share/kibana/config/certs/ca.crt"
        # Kibana server settings
        - name: SERVER_SSL_ENABLED
          value: "false"
        - name: SERVER_HOST
          value: "0.0.0.0"
        # Remove service account token as we're using username/password
        - name: ELASTICSEARCH_SERVICEACCOUNTTOKEN
          value: ""
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
        volumeMounts:
        - name: elasticsearch-ca-certs
          mountPath: "/usr/share/kibana/config/certs"
          readOnly: true
        # Add readiness and liveness probes
        readinessProbe:
          httpGet:
            path: /api/status
            port: 5601
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/status
            port: 5601
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 30
      volumes:
      - name: elasticsearch-ca-certs
        secret:
          secretName: elastic-cluster-es-ca # ECK creates this secret automatically
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elastic-system
  labels:
    component: kibana
spec:
  type: NodePort
  selector:
    component: kibana
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 30017
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kibana-sa
  namespace: elastic-system