{
 "title": "Slow queries v1.1",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds)"
   },
   {
    "name": "release",
    "label": "Release",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds{kubernetes_namespace=\"$namespace\"})"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result(pg_up{release=\"$release\"})"
   },
   { "name": "datname", "label": "Database", "query": "label_values(datname)" },
   {
    "name": "mode",
    "label": "Lock table",
    "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
   }
  ]
 },
 "panels": [
  {
   "title": "Heartbeat (from pg_stat_activity)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "interval",
   "collapsed": true,
   "panels": [
    {
     "title": "active queries by database",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": " count(pg_long_running_active_queries_seconds_query_duration_seconds{instance=\"$instance\",datname=~\"$datname\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "count by (datname) (pg_long_running_active_queries_seconds_query_duration_seconds{instance=\"$instance\",datname=~\"$datname\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active queries",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "topk(100, sum(pg_long_running_active_queries_seconds_query_duration_seconds{instance=\"$instance\",datname=~\"$datname\"}) by (pid, datname, usename, client_addr, application_name, state, wait_event_type, wait_event, query_hash)) > 0"
      }
     ]
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Connections By state",
   "type": "bargauge",
   "description": "from table pg_stat_activity",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (rolname) ((pg_stat_activity_count{instance=\"$instance\",datname=~\"$datname\"})) > 0 ",
     "legendFormat": "Total Connections"
    },
    {
     "expr": "sum by (state) ((pg_stat_activity_count{instance=\"$instance\",datname=~\"$datname\"})) > 0",
     "legendFormat": "{{rolname}}"
    }
   ]
  },
  {
   "title": "Active connections by databases",
   "type": "gauge",
   "description": "Displays the total number of active connections to your PostgreSQL databases.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"active\",instance=\"$instance\"}) by (datname) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backends connections by database",
   "type": "gauge",
   "description": "Shows the number of backend processes currently connected to each database. This includes all states (active, idle, idle in transaction, etc.).",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(pg_stat_database_numbackends{instance=\"$instance\"}) > 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Total Active Connections on databases",
   "type": "timeseries",
   "description": "Displays the total number of active connections to your PostgreSQL databases.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"active\",instance=\"$instance\"}) by (datname) > 0 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Backends Connections on database",
   "type": "timeseries",
   "description": "Shows the number of backend processes currently connected to each database. This includes all states (active, idle, idle in transaction, etc.).",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "(pg_stat_database_numbackends{instance=\"$instance\"}) > 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max Logical Replication Workers",
     "type": "stat",
     "description": "Shows the configured max_logical_replication_workers setting.",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 242 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "  (pg_settings_max_logical_replication_workers{instance=\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Number of Active Replication Slots",
     "type": "stat",
     "description": "This helps ensure that your replication slots are active and haven't failed.",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 242 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "  sum(pg_replication_slots_active{instance=\"$instance\"}) by (slot_type)",
       "legendFormat": "{{slot_type}}"
      }
     ]
    },
    {
     "title": "Replication Slots WAL Lag (bytes)",
     "type": "stat",
     "description": "amount of WAL data, in bytes, that has accumulated since the restart_lsn of the replication slot",
     "gridPos": { "h": 2, "w": 5, "x": 12, "y": 242 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_replication_slots_wal_bytes_lag{instance=\"$instance\"})"
      }
     ]
    },
    {
     "title": "Replication Lag (Seconds)",
     "type": "timeseries",
     "description": "Measures the time delay, in seconds, between the primary and replica servers. This is a critical metric for replication health.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 244 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (state,application_name,sync_state) (pg_replication_lag_seconds_estimate_lag_seconds_estimate{instance=\"$instance\",})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Replication slots status",
     "type": "bargauge",
     "description": "Whether the replication slot is currently active (1) or inactive (0).",
     "gridPos": { "h": 16, "w": 4, "x": 12, "y": 244 },
     "targets": [
      {
       "expr": "count (pg_replication_slots_active{instance=\"$instance\"})",
       "legendFormat": "total"
      },
      {
       "expr": "count by (slot_name,slot_type)(pg_replication_slots_active{instance=\"$instance\"})",
       "legendFormat": "{{slot_name}} : {{slot_type}}"
      }
     ]
    },
    {
     "title": "Replication Slot Lag (Bytes)",
     "type": "timeseries",
     "description": "Shows the difference in Write-Ahead Log (WAL) Sequence Numbers (LSN) for replication slots, indicating lag in bytes per slot.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 251 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "(pg_replication_slots_wal_bytes_lag{instance=\"$instance\"})",
       "legendFormat": "  plugin={{plugin}}, slot_name={{slot_name}}, slot_type={{slot_type}}, wal_status={{wal_status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Historical (from pg_stat_statments)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "repeat": "interval",
   "collapsed": true,
   "panels": [
    {
     "title": "Excessive Queries by Database",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 141 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (datname) (pg_stat_statements_calls{instance=\"$instance\",datname=~\"$datname\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max transaction duration",
     "type": "timeseries",
     "description": "max duration in seconds any active transaction has been running",
     "gridPos": { "h": 10, "w": 17, "x": 7, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(pg_stat_activity_max_tx_duration{instance=\"$instance\", datname=~\"$datname\",state=~\"active|idle*\"}) > 0",
       "legendFormat": "{{state}} : {{application_name}} : {{backend_type}} : {{datname}} : {{usename}} : {{wait_event}} : {{wait_event_type}}"
      }
     ]
    },
    {
     "title": "Total active connections",
     "type": "timeseries",
     "description": "This system view provides information about current database activity, including user names and query execution details. ",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 151 },
     "targets": [
      {
       "expr": "sum by (usename) ((pg_stat_activity_count{instance=\"$instance\",datname=~\"$datname\"})) ",
       "legendFormat": "{{usename}}"
      }
     ]
    },
    {
     "title": "Last executed queries",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 161 },
     "targets": [
      {
       "expr": "pg_stat_statements_calls{instance=\"$instance\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "pg_stat_statements_total_time_seconds{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of Query calls by 5m",
     "type": "timeseries",
     "description": "Number of times query called by user",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 171 },
     "targets": [
      {
       "expr": "rate(pg_stat_statements_calls{instance=\"$instance\", rolname!=\"postgres_exporter\"}[5m])",
       "legendFormat": "USER: {{rolname}}, DB: {{datname}}, QRY:  {{query}}"
      }
     ]
    },
    {
     "title": "Top 10 Queries by Total Execution Time",
     "type": "timeseries",
     "description": "Displays the top 10 queries with the highest total execution time across the selected instance and database. This helps identify performance bottlenecks in your PostgreSQL queries.",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(topk(10, pg_stat_statements_total_time_seconds{instance=\"$instance\", datname=~\"$datname\",rolname!=\"postgres\"}))",
       "legendFormat": "USER: {{rolname}}, DB: {{datname}}, QRY:  {{query}}"
      }
     ]
    }
   ]
  }
 ]
}