{
 "title": "Hosts Insights",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(node_disk_info,instance)"
    }
   },
   {
    "name": "db_node",
    "label": "Postgres Instance",
    "query": {
     "query": "label_values(node_disk_info{job=\"node-exporter\"},instance)"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(node_disk_info{instance=~\"$node\"},app)"
    }
   },
   { "name": "route", "label": "Route", "query": { "query": "label_values(http_route)" } },
   { "name": "org_type", "label": "Org Type", "query": { "query": "label_values(org_type)" } },
   {
    "name": "org_id",
    "label": "Org ID",
    "query": {
     "query": "label_values(http_request_duration_seconds_count{org_type=\"$org_type\"},org_id)"
    }
   },
   {
    "name": "user_name",
    "label": "user ID",
    "query": {
     "query": "label_values(http_request_duration_seconds_count{org_type=\"$org_type\", org_id=\"$org_id\"},user_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Infra Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sys Load [1m]",
   "type": "gauge",
   "description": "System load  over all CPU cores together",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(node_load1{instance=~\"$node\", app=~\"$app\"},\"instance\",\"$1.$2.$3.$4\",\"instance\",\"^(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)(?::\\\\d+)?$\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Space Used% Basic (Application) - ['$node']",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(((node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\" }-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"})) )> 50,\"instance\",\"$1.$2.$3.$4\",\"instance\",\"^(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)(?::\\\\d+)?$\")",
     "legendFormat": "{{instance}} : {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Sys Load [5m]",
   "type": "gauge",
   "description": "System load  over all CPU cores together",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(node_load5{instance=~\"$node\", app=~\"$app\"},\"instance\",\"$1.$2.$3.$4\",\"instance\",\"^(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)(?::\\\\d+)?$\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Sys Load [15m]",
   "type": "gauge",
   "description": "System load  over all CPU cores together",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(node_load15{instance=~\"$node\", app=~\"$app\"},\"instance\",\"$1.$2.$3.$4\",\"instance\",\"^(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)(?::\\\\d+)?$\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node resources usage (Application) - [$node]",
   "type": "table",
   "description": "- *Load* - CPU capasity used (load average for last 1 minute divided by CPU cores count)\n- *CPU* - CPU usage\n- *Memory* - memory usage\n- *Filesystem* - filesystem usage\n- *Disk read* - maximum among all disks read rate\n- *Dist write* - maximum among all disks write rate\n- *Net recv* - maximum among all NIC's receive rate\n- *Net trans* - maximum among all NIC's transmit rate\n- *Net sock* - used network sockets \n- *TCP estab* - TCP established connections\n- *TCP tw* - TCP sockets in TIME-WAIT status",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "label_replace(node_uname_info{instance=~\"$node\"},\"instance\",\"$1.$2.$3.$4\",\"instance\",\"^(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)(?::\\\\d+)?$\")"
    },
    {
     "expr": "label_replace((1 - avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$__rate_interval])) by (instance)) * 100,\"instance\",\"$1.$2.$3.$4\",\"instance\",\"^(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)(?::\\\\d+)?$\")"
    },
    {
     "expr": "label_replace((1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"}))) * 100,\"instance\",\"$1.$2.$3.$4\",\"instance\",\"^(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)(?::\\\\d+)?$\")"
    },
    {
     "expr": "label_replace(max((1 - (node_filesystem_free_bytes{instance=~\"$node\"} / node_filesystem_size_bytes{instance=~\"$node\"})) * 100) by (instance),\"instance\",\"$1.$2.$3.$4\",\"instance\",\"^(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)(?::\\\\d+)?$\")"
    },
    {
     "expr": "label_replace(max(rate(node_disk_read_bytes_total{instance=~\"$node\"}[$__rate_interval])) by (instance),\"instance\",\"$1.$2.$3.$4\",\"instance\",\"^(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)(?::\\\\d+)?$\")"
    },
    {
     "expr": "label_replace(max(rate(node_disk_written_bytes_total{instance=~\"$node\"}[$__rate_interval])) by (instance),\"instance\",\"$1.$2.$3.$4\",\"instance\",\"^(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)(?::\\\\d+)?$\")"
    },
    {
     "expr": "label_replace(node_netstat_Tcp_CurrEstab{instance=~\"$node\"} - 0,\"instance\",\"$1.$2.$3.$4\",\"instance\",\"^(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)(?::\\\\d+)?$\")"
    },
    {
     "expr": "label_replace(node_sockstat_TCP_tw{instance=~\"$node\"} - 0,\"instance\",\"$1.$2.$3.$4\",\"instance\",\"^(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)(?::\\\\d+)?$\")"
    },
    {
     "expr": "label_replace(max(rate(node_network_receive_bytes_total{instance=~\"$node\"}[$__rate_interval])*8) by (instance),\"instance\",\"$1.$2.$3.$4\",\"instance\",\"^(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)(?::\\\\d+)?$\")"
    },
    {
     "expr": "label_replace(max(rate(node_network_transmit_bytes_total{instance=~\"$node\"}[$__rate_interval])*8) by (instance),\"instance\",\"$1.$2.$3.$4\",\"instance\",\"^(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)(?::\\\\d+)?$\")"
    },
    {
     "expr": "label_replace(avg(node_load1{instance=~\"$node\"} * 100) by (instance) / count (node_cpu_seconds_total{instance=~\"$node\", mode=\"system\"}) by (instance),\"instance\",\"$1.$2.$3.$4\",\"instance\",\"^(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)(?::\\\\d+)?$\")"
    },
    {
     "expr": "label_replace(node_sockstat_sockets_used{instance=~\"$node\"},\"instance\",\"$1.$2.$3.$4\",\"instance\",\"^(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)(?::\\\\d+)?$\")"
    },
    {
     "expr": "label_replace(((node_memory_SwapTotal_bytes{instance=~\"$node\",app=~\"$app\"} - node_memory_SwapFree_bytes{instance=~\"$node\",app=~\"$app\"}) / (node_memory_SwapTotal_bytes{instance=~\"$node\",app=~\"$app\"})) * 100,\"instance\",\"$1.$2.$3.$4\",\"instance\",\"^(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)\\\\.(\\\\d+)(?::\\\\d+)?$\")"
    }
   ]
  }
 ]
}