{
 "title": "Rate Analysis Dashboard New",
 "description": "A language-agnostic application performance management(APM) with OpenTelemetry, Grafana, and Prometheus.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "app", "label": "Application", "query": { "query": "label_values(exported_job)" } },
   { "name": "route", "label": "Route", "query": { "query": "label_values(http_route)" } }
  ]
 },
 "panels": [
  {
   "title": "Overall Request Rate",
   "type": "stat",
   "description": "overall request rate per minute over last 3 minutes",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{exported_job=\"$app\", http_route=~\"$route\"}[$__range])*60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average HTTP Request Duration (Top 5 Routes)",
   "type": "timeseries",
   "description": "calculates the average HTTP request duration for the top 5 routes with the highest request durations over the past 3 minutes",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, sort_desc(rate(http_server_request_duration_seconds_sum{http_response_status_code!=\"\", http_route=~\"$route\", exported_job=\"$app\"}[3m]))) / rate(http_server_request_duration_seconds_count{http_response_status_code!=\"\", http_route=~\"$route\", exported_job=\"$app\"}[3m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Request",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{exported_job=\"$app\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Count per Route (Per Minute)",
   "type": "timeseries",
   "description": "calculates the per-minute HTTP request count for each route over the past 3 minutes.",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(http_route) (rate(http_server_request_duration_seconds_count{http_route=~\"$route\", exported_job=\"$app\"}[3m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Error Rate",
   "type": "stat",
   "description": "percentage of HTTP status 5xx in all requests",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{http_response_status_code=~\"4.*|5.*\", http_route=~\"$route\", exported_job=\"$app\"}[$__range])) / sum(rate(http_server_request_duration_seconds_count{http_route=~\"$route\", exported_job=\"$app\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Error Request Count per Route (4xx & 5xx)",
   "type": "timeseries",
   "description": "calculates the per-minute count of HTTP requests resulting in client-side (4xx) and server-side (5xx) errors for each route over the past 3 minutes",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(http_route) (rate(http_server_request_duration_seconds_count{http_route=~\"$route\", exported_job=\"$app\", http_response_status_code!=\"200\"}[3m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Error Distribution by Duration (4xx & 5xx)",
   "type": "timeseries",
   "description": "calculates the distribution of HTTP errors (4xx & 5xx status codes) by request duration for each route",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(le, http_route) (rate(http_server_request_duration_seconds_bucket{exported_job=\"$app\", http_route=~\"$route\", http_response_status_code=\"500\"}[3m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Slowest Routes by 95th Percentile Response Time",
   "type": "timeseries",
   "description": "Top 5 routes with the highest 95th percentile response times in your application",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, histogram_quantile(0.95, sum by(le, http_route) (rate(http_server_request_duration_seconds_bucket{exported_job=\"$app\", http_route=~\"$route\"}[3m]))))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}