{
 "title": "K8S Dashboard [Jun 2025]",
 "description": "【English version】2025.01.25 Updates，kubernetesComprehensive display of resources！Includes K8S Overall Resource Overview、Microservices Resource Details、Pod Resource Details andK8SNetwork Bandwidth，Optimization metrics。https://grafana.com/orgs/starsliao/dashboards",
 "tags": [
  "Prometheus",
  "Kubernetes"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "origin_prometheus", "label": "K8S", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kube_pod_info,instance)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(kube_state_metrics_build_info,job)"
    }
   },
   {
    "name": "Node",
    "label": "Nodes",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   },
   {
    "name": "NameSpace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created{job=~\"$job\"},namespace)"
    }
   },
   {
    "name": "Container",
    "label": "Microservice (Container Name)",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$NameSpace\"},container)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$NameSpace\", container=~\"$Container\"},pod)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Node Resource Overview：Selected Nodes:【$Node】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Node Memory Ratio",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
     "legendFormat": "Memory Request Rate"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
     "legendFormat": "Memory Limit Rate"
    }
   ]
  },
  {
   "title": "Node CPU Ratio",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{container!=\"\",node=~\"^$Node$\"}[2m])) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
     "legendFormat": "CPU Utilization Rate"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
     "legendFormat": "CPU Request Rate"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
     "legendFormat": "CPU Limit Rate"
    }
   ]
  },
  {
   "title": "Nodes with Pod",
   "type": "bargauge",
   "description": "Number of cluster nodes，Nodes POD Number of，NodesPODUpper Limit",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{job=~\"$job\"})",
     "legendFormat": "Number of nodes"
    },
    {
     "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\",node=~\"^$Node$\"})",
     "legendFormat": "Pod Number of nodes"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"pods\", unit=\"integer\",node=~\"^$Node$\"})",
     "legendFormat": "Upper limit Pod"
    }
   ]
  },
  {
   "title": "Namespace Resource Statistics",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kube_pod_info{node=~\"^$Node$\"}) by (namespace)"
    },
    {
     "expr": "count(kube_service_info{job=~\"$job\"}) by(namespace)"
    },
    {
     "expr": "count by (namespace)({__name__=~\"kube_deployment_metadata_generation|kube_daemonset_metadata_generation|kube_statefulset_metadata_generation\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(kube_configmap_info{job=~\"$job\"}) by(namespace)",
     "legendFormat": "configmap"
    },
    {
     "expr": "count(kube_secret_info{job=~\"$job\"}) by(namespace)",
     "legendFormat": "secret"
    }
   ]
  },
  {
   "title": "Node Memory Information",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{container!=\"\",node=~\"^$Node$\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Node CPU Number of cores",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
     "legendFormat": "Total Cores"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{id=\"/\",node=~\"^$Node$\"}[2m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Node Storage Information",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})",
     "legendFormat": "Utilization Rate"
    },
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 12 },
   "repeat": "origin_prometheus",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count({__name__=~\"kube_deployment_metadata_generation|kube_daemonset_metadata_generation|kube_statefulset_metadata_generation\",instance=~\"$instance\"})",
     "legendFormat": "Workload"
    },
    {
     "expr": "count(kube_pod_info{namespace=~\"$NameSpace\"})",
     "legendFormat": "Total Pod"
    },
    {
     "expr": "count by(key,instance)(kube_node_spec_taint{instance=~\"$instance\",key=~\"node.kubernetes.io.*\"})",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "count by(instance)(kube_node_info{instance=~\"$instance\"})",
     "legendFormat": "Total Nodes"
    },
    {
     "expr": "count by(instance)(kube_node_info{instance=~\"$instance\"}) - count by(instance)(kube_node_spec_taint{instance=~\"$instance\",key!~\"node.kubernetes.io.*\"})",
     "legendFormat": "Worker Node"
    },
    {
     "expr": "count by(instance)(kube_node_spec_taint{instance=~\"$instance\",key!~\"node.kubernetes.io.*\"})",
     "legendFormat": "Master Node"
    }
   ]
  },
  {
   "title": "Memory Usage【$Node】",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "CPU Used Cores【$Node】",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Pod Number and nodes【$Node】",
   "type": "timeseries",
   "description": "Number of Cluster Nodes，Nodes POD Number of，Nodes POD Upper Limit",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kube_node_info{instance=~\"$instance\"})",
     "legendFormat": "Number of nodes"
    },
    {
     "expr": "count(kube_pod_info{instance=~\"$instance\",created_by_kind!~\"<none>|Job\",node=~\"^$Node$\"})",
     "legendFormat": "Pod Number"
    },
    {
     "expr": "sum(kube_node_status_allocatable{instance=~\"$instance\",resource=\"pods\", unit=\"integer\",node=~\"^$Node$\"})",
     "legendFormat": "Upper Limit Pod"
    }
   ]
  },
  {
   "title": "$Node：Node Information Detail",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\",node=~\"^$Node$\",instance=~\"$instance\"}) by (node)",
     "legendFormat": "pod Number"
    },
    {
     "expr": "kube_node_status_condition{instance=~\"$instance\",status=\"true\",node=~\"^$Node$\"}  == 1",
     "legendFormat": "Status"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{instance=~\"$instance\",container!=\"\",node=~\"^$Node$\"}[2m])) by (node)"
    },
    {
     "expr": "kube_node_status_allocatable{instance=~\"$instance\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"} - 0"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{instance=~\"$instance\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{instance=~\"$instance\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum(kube_node_status_allocatable{instance=~\"$instance\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"}) by (node) - 0"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{instance=~\"$instance\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{instance=~\"$instance\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum (container_fs_usage_bytes{instance=~\"$instance\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum (container_fs_limit_bytes{instance=~\"$instance\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum(kube_node_status_allocatable{instance=~\"$instance\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})by (node)",
     "legendFormat": "Memory Usage%"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{instance=~\"$instance\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{instance=~\"$instance\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})by (node)",
     "legendFormat": "Memory Requests%"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{instance=~\"$instance\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{instance=~\"$instance\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})by (node)",
     "legendFormat": "Memory Limit%"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{instance=~\"$instance\",container!=\"\",node=~\"^$Node$\"}[2m]))by (node) / sum(kube_node_status_allocatable{instance=~\"$instance\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node)",
     "legendFormat": "CPU Usage%"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{instance=~\"$instance\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{instance=~\"$instance\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node)",
     "legendFormat": "CPU Requests%"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{instance=~\"$instance\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{instance=~\"$instance\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node)",
     "legendFormat": "Memory Limit%"
    },
    {
     "expr": "sum (container_fs_usage_bytes{instance=~\"$instance\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})by (node) / sum (container_fs_limit_bytes{instance=~\"$instance\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})by (node)",
     "legendFormat": "Disk Usage%"
    },
    {
     "expr": "sum(kube_node_status_allocatable{instance=~\"$instance\",resource=\"pods\", unit=\"integer\",node=~\"^$Node$\"})by (node)",
     "legendFormat": "PodCaps"
    }
   ]
  },
  {
   "title": "PVC Storage Usage",
   "type": "table",
   "gridPos": { "h": 16, "w": 18, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "min by (namespace,persistentvolumeclaim) (kube_persistentvolumeclaim_resource_requests_storage_bytes{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (namespace,persistentvolumeclaim) (kube_persistentvolumeclaim_created{instance=~\"$instance\"})",
     "legendFormat": "{{namespace}}:{{ persistentvolumeclaim }}"
    },
    {
     "expr": "count by (phase,persistentvolumeclaim)(kube_persistentvolumeclaim_status_phase{instance=~\"$instance\"})",
     "legendFormat": "{{phase}}:{{ persistentvolumeclaim }}"
    },
    {
     "expr": "count by (namespace,persistentvolumeclaim)(kube_pod_spec_volumes_persistentvolumeclaims_info{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Node：Node Network Overview",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum (irate(node_network_receive_bytes_total{node=~\"^$Node$\"}[2m]))by (node) *8",
     "legendFormat": "Inflow:{{node}}"
    },
    {
     "expr": "sum (irate(node_network_receive_bytes_total{node=~\"^$Node$\"}[2m]))by (node) *8",
     "legendFormat": "Outflows:{{node}}"
    }
   ]
  },
  {
   "title": "Pod Resource Overview：SelectedPod:【$Pod】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 }
  },
  {
   "title": "$Node：Pod Resource Detail(Associable Nodes)",
   "type": "table",
   "gridPos": { "h": 18, "w": 16, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"$Pod\",container =~\"$Container\",instance=~\"$instance\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (container, pod,node,namespace) / (sum(container_spec_cpu_quota{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\",instance=~\"$instance\"}/100000) by (container, pod,node,namespace)) "
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{instance=~\"$instance\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (container, pod,node,namespace)",
     "legendFormat": "CPUKernel Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{instance=~\"$instance\",resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{instance=~\"$instance\",resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{instance=~\"$instance\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)/ sum(container_spec_memory_limit_bytes{instance=~\"$instance\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)",
     "legendFormat": "wss%"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{instance=~\"$instance\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)",
     "legendFormat": "wss"
    },
    {
     "expr": "sum (container_memory_rss{instance=~\"$instance\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)/ sum(container_spec_memory_limit_bytes{instance=~\"$instance\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)",
     "legendFormat": "rss%"
    },
    {
     "expr": "sum (container_memory_rss{instance=~\"$instance\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)",
     "legendFormat": "rss"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{instance=~\"$instance\",resource=\"memory\", unit=\"byte\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{instance=~\"$instance\",resource=\"memory\", unit=\"byte\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum(container_fs_usage_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{instance=~\"$instance\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"} * on (pod) group_left(node) kube_pod_info{instance=~\"$instance\",pod=~\"$Pod\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}"
    },
    {
     "expr": "time() - kube_pod_created{instance=~\"$instance\",pod=~\"$Pod\",namespace=~\"$NameSpace\"} * on(pod) group_right kube_pod_container_info{instance=~\"$instance\",pod=~\"$Pod\",namespace=~\"$NameSpace\",container =~\"$Container\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_fs_limit_bytes{instance=~\"$instance\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum(sum(irate(container_network_receive_bytes_total{instance=~\"$instance\",pod=~\"$Pod\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{instance=~\"$instance\",pod=~\"$Pod\",namespace=~\"$NameSpace\",container =~\"$Container\"}) by(pod) *8",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sum(irate(container_network_transmit_bytes_total{instance=~\"$instance\",pod=~\"$Pod\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{instance=~\"$instance\",pod=~\"$Pod\",namespace=~\"$NameSpace\",container =~\"$Container\"}) by(pod) *8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Containers WSS Memory Usage (Associable Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max (container_memory_working_set_bytes{instance=~\"$instance\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)",
     "legendFormat": "WSS：{{ pod }}"
    },
    {
     "expr": "max(max(kube_pod_container_resource_limits{instance=~\"$instance\",resource=\"memory\", unit=\"byte\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)) by(container)",
     "legendFormat": "PodMemory Limits：{{ container}}"
    }
   ]
  },
  {
   "title": "Pod Containers CPU Core Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(irate(container_cpu_usage_seconds_total{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (container, pod,node,namespace)",
     "legendFormat": "CPU Usage：{{ pod }}"
    },
    {
     "expr": "max(max(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)) by(container)",
     "legendFormat": "Pod CPU Limitations：{{ container}}"
    }
   ]
  },
  {
   "title": "Microservices (Container Name) Resource Overview：Selected Microservices:【$Container】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Microservices (Container Name) Resource Statistics",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container) / (sum(container_spec_cpu_quota{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}/100000) by (container))"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container)",
       "legendFormat": "Total Cores Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{origin_prometheus=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{origin_prometheus=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
       "legendFormat": "Average Memory%(RSS)"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
       "legendFormat": "Total Memory Usage (RSS) "
      },
      {
       "expr": "sum by(container) (kube_pod_container_resource_requests{origin_prometheus=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"})"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{origin_prometheus=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "avg(container_fs_usage_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "count(kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by(container,namespace)"
      },
      {
       "expr": "avg(container_fs_limit_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      }
     ]
    },
    {
     "title": "Microservices (Container Name) Average CPU Usage (Maximum100%)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container) / (sum(container_spec_cpu_quota{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}/100000) by (container)) * 100",
       "legendFormat": "{{ container}}"
      }
     ]
    },
    {
     "title": "Microservices (Container Name) Overall Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
       "legendFormat": "WSS：{{ container }}"
      },
      {
       "expr": "sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
       "legendFormat": "Memory Limit：{{ container }}"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
       "legendFormat": "RSS：{{ container }}"
      }
     ]
    },
    {
     "title": "Microservice (Container Name) Pod Number",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by(container,namespace)",
       "legendFormat": "{{namespace}}：{{ container }}"
      }
     ]
    },
    {
     "title": "Microservices (Container Name) Overall CPU Cores Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{origin_prometheus=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
       "legendFormat": "CPU Limitations：{{ container}}"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container)",
       "legendFormat": "CPU Core Usage：{{ container}}"
      }
     ]
    },
    {
     "title": "Microservice (Container Name) Average Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container) * 100",
       "legendFormat": "WSS：{{ container }}"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container) * 100",
       "legendFormat": "RSS：{{ container }}"
      }
     ]
    },
    {
     "title": "Microservice (Container Name) Network bandwidth per second (Associable Nodes)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "expr": "sum(sum(irate(container_network_receive_bytes_total{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",namespace=~\"$NameSpace\",container =~\"$Container\"}) by(container) *8",
       "legendFormat": "Inflow:{{ container }}"
      },
      {
       "expr": "sum(sum(irate(container_network_transmit_bytes_total{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",namespace=~\"$NameSpace\",container =~\"$Container\"}) by(container) *8",
       "legendFormat": "Outflow:{{ container }}"
      }
     ]
    }
   ]
  }
 ]
}