{
 "title": "etcd",
 "description": "etcd sample Grafana dashboard with Prometheus",
 "tags": [ "etcd-mixin" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(etcd_server_has_leader{job=~\".*etcd.*\"}, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(etcd_server_has_leader{job=~\".*etcd.*\", job=\"$cluster\"})",
     "legendFormat": "{{cluster}} - {{namespace}}\n"
    }
   ]
  },
  {
   "title": "RPC rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=~\".*etcd.*\", job=\"$cluster\",grpc_type=\"unary\"}[$__rate_interval]))",
     "legendFormat": "RPC rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{job=~\".*etcd.*\", job=\"$cluster\",grpc_type=\"unary\",grpc_code=~\"Unknown|FailedPrecondition|ResourceExhausted|Internal|Unavailable|DataLoss|DeadlineExceeded\"}[$__rate_interval]))",
     "legendFormat": "RPC failed rate"
    }
   ]
  },
  {
   "title": "Active streams",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(grpc_server_started_total{job=~\".*etcd.*\",job=\"$cluster\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{job=\"$cluster\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Watch streams"
    },
    {
     "expr": "sum(grpc_server_started_total{job=~\".*etcd.*\",job=\"$cluster\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{job=\"$cluster\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Lease streams"
    }
   ]
  },
  {
   "title": "DB size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{job=~\".*etcd.*\", job=\"$cluster\"}",
     "legendFormat": "{{instance}} DB size"
    }
   ]
  },
  {
   "title": "Disk sync duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=~\".*etcd.*\", job=\"$cluster\"}[$__rate_interval])) by (instance, le))",
     "legendFormat": "{{instance}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{job=~\".*etcd.*\", job=\"$cluster\"}[$__rate_interval])) by (instance, le))",
     "legendFormat": "{{instance}} DB fsync"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\".*etcd.*\", job=\"$cluster\"}",
     "legendFormat": "{{instance}} resident memory"
    }
   ]
  },
  {
   "title": "Client traffic in",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{job=~\".*etcd.*\", job=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{instance}} client traffic in"
    }
   ]
  },
  {
   "title": "Client traffic out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{job=~\".*etcd.*\", job=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{instance}} client traffic out"
    }
   ]
  },
  {
   "title": "Peer traffic in",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total{job=~\".*etcd.*\", job=\"$cluster\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}} peer traffic in"
    }
   ]
  },
  {
   "title": "Peer traffic out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total{job=~\".*etcd.*\", job=\"$cluster\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}} peer traffic out"
    }
   ]
  },
  {
   "title": "Raft proposals",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{job=~\".*etcd.*\", job=\"$cluster\"}[1d])",
     "legendFormat": "{{instance}} total leader elections per day"
    }
   ]
  },
  {
   "title": "Total leader elections per day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{job=~\".*etcd.*\", job=\"$cluster\"}[1d])",
     "legendFormat": "{{instance}} total leader elections per day"
    }
   ]
  },
  {
   "title": "Peer round trip time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (instance, le) (rate(etcd_network_peer_round_trip_time_seconds_bucket{job=~\".*etcd.*\", job=\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "{{instance}} peer round trip time"
    }
   ]
  }
 ]
}