---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-kafka-consumer-config
  namespace: serversage-app
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name              kafka
        Brokers           kafka.kafka.svc.cluster.local:9092
        Topics            kubernetes-logs
        Group_Id          flb-consumer-group
        Format            json
        Tag               kafka.logs

    [OUTPUT]
        Name                es
        Match               kafka.logs
        Host                elasticsearch.elasticsearch.svc.cluster.local
        Port                9200
        Index               kubernetes-logs
        Log_Level           trace             # Recommended for debugging, change to info/warn for production
        Suppress_Type_Name  On                # Replaces 'Type' key with 'TypeName' to avoid conflicts
        TLS                 Off               # Set to On if your Elasticsearch uses HTTPS
        TLS.Verify          Off               # Set to On if TLS is On and you want to verify the certificate
        Buffer_Size         20MB
        Trace_Error         On                # Use Trace_Error instead of TraceError
        Time_Key            @timestamp        # Use Time_Key instead of timeKey
        Replace_Dots        On
        Retry_Limit         5
        Generate_ID         On                # Use Generate_ID instead of GenerateId (already present but for clarity)
        # Optional: If you need to set a custom document ID
        # If using API key authentication
        # Https_User        <your_api_key_id>
        # Https_Passwd      <your_api_key_secret>
        # If using basic authentication
        # HTTP_User         <your_username>
        # HTTP_Passwd       <your_password>
  parsers.conf: |
    [PARSER]
        Name   json
        Format json
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-bit-kafka-consumer
  namespace: serversage-app
  labels:
    app: fluent-bit-kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluent-bit-kafka-consumer
  template:
    metadata:
      labels:
        app: fluent-bit-kafka-consumer
    spec:
      containers:
        - name: fluent-bit
          image: cr.fluentbit.io/fluent/fluent-bit:2.2.2
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/
      volumes:
        - name: config
          configMap:
            name: fluent-bit-kafka-consumer-config
