# first-cluster.yml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  - role: control-plane
    image: kindest/node:v1.33.0
    extraMounts:
    - hostPath: ./kind-data
      containerPath: /kind-data
    extraPortMappings:
      - containerPort: 80 # cluster port
        hostPort: 85   # host port 
        protocol: TCP # It's good practice to specify the protocol
      - containerPort: 443
        hostPort: 445
        protocol: TCP # It's good practice to specify the protocol
      - containerPort: 30012
        hostPort: 30012
        protocol: TCP
      - containerPort: 30013
        hostPort: 30013
        protocol: TCP
      - containerPort: 30014
        hostPort: 30014
        protocol: TCP
      - containerPort: 30015
        hostPort: 30015
        protocol: TCP
      - containerPort: 30016
        hostPort: 30016
        protocol: TCP
      - containerPort: 30017
        hostPort: 30017
        protocol: TCP
      - containerPort: 30018
        hostPort: 30018
        protocol: TCP
      - containerPort: 30019
        hostPort: 30019
        protocol: TCP
  - role: worker
    image: kindest/node:v1.33.0
  - role: worker
    image: kindest/node:v1.33.0
  # - role: worker
  #   image: kindest/node:v1.32.2
