---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-connect-config
  namespace: serversage-app
data:
  CONNECT_BOOTSTRAP_SERVERS: kafka.kafka.svc.cluster.local:9092
  CONNECT_REST_PORT: "8083"
  CONNECT_GROUP_ID: kafka-connect-cluster
  CONNECT_CONFIG_STORAGE_TOPIC: _connect-configs
  CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
  CONNECT_STATUS_STORAGE_TOPIC: _connect-status
  CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
  CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
  CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
  CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
  CONNECT_LOG4J_LOGGERS: org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR
  CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components
  CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
  namespace: serversage-app
  labels:
    app: kafka-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      containers:
        - name: kafka-connect
          image: confluentinc/cp-kafka-connect:7.5.0
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: kafka-connect-config
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
  namespace: serversage-app
spec:
  selector:
    app: kafka-connect
  ports:
    - port: 8083
      targetPort: 8083
