{
 "title": "BseStarMF Application API Usage",
 "description": "Application API usage dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "app", "label": "Application", "query": { "query": "label_values(exported_job)" } },
   { "name": "route", "label": "Route", "query": { "query": "label_values(http_route)" } },
   { "name": "org_type", "label": "Org Type", "query": { "query": "label_values(org_type)" } },
   {
    "name": "org_id",
    "label": "Org ID",
    "query": {
     "query": "label_values(http_request_duration_seconds_count{org_type=\"$org_type\"},org_id)"
    }
   },
   {
    "name": "user_name",
    "label": "user ID",
    "query": {
     "query": "label_values(http_request_duration_seconds_count{org_type=\"$org_type\", org_id=\"$org_id\"},user_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overall Request Rate",
   "type": "stat",
   "description": "overall request rate per minute over last 3 minutes",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{http_route=~\"$route\", exported_job=\"$app\", org_type=\"$org_type\", org_id=\"$org_id\", user_name=\"$user_name\"}[$__range])) * 60"
    }
   ]
  },
  {
   "title": "Request Distribution",
   "type": "piechart",
   "description": "request amount distribution",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_route) (rate(http_request_duration_seconds_count{http_route=~\"$route\", exported_job=\"$app\", org_type=~\"$org_type\", org_id=\"$org_id\", user_name=\"$user_name\"}[$__range]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Loading Distribution",
   "type": "piechart",
   "description": "cumulative latency distribution",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_response_status_code) (increase(http_request_duration_seconds_count{http_route=~\"$route\", exported_job=\"$app\", org_type=\"$org_type\", org_id=\"$org_id\", user_name=\"$user_name\"}[$__range]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{exported_job=\"$app\", org_type=\"$org_type\", org_id=\"$org_id\", user_name=\"$user_name\"}[$__range])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Error percentage",
   "type": "gauge",
   "description": "percentage of HTTP status 5xx in all requests",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{http_response_status_code=~\"4.*|5.*\", http_route=~\"$route\", exported_job=\"$app\", org_type=\"$org_type\", org_id=\"$org_id\", user_name=\"$user_name\"}[$__range])) / sum(rate(http_request_duration_seconds_count{http_route=~\"$route\", exported_job=\"$app\", org_type=\"$org_type\", org_id=\"$org_id\", user_name=\"$user_name\"}[$__range])) "
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "request rate per minute over last 3 minutes",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "topk(5, sum by(http_route) (rate(http_request_duration_seconds_count{http_route=~\"$route\", exported_job=\"$app\", org_type=\"$org_type\", org_id=\"$org_id\", user_name=\"$user_name\"}[3m]))) * 60",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "PR95 Latency",
   "type": "timeseries",
   "description": "PR95 latency over last 3 minutes",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{ http_route=~\"$route\",exported_job=\"$app\", org_type=\"$org_type\", org_id=\"$org_id\", user_name=\"$user_name\"}[3m])) by (le, http_route))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "bargauge",
   "description": "by route and http status code",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sort_desc(increase(http_request_duration_seconds_sum{http_response_status_code!=\"\", http_route=~\"$route\", exported_job=\"$app\", org_type=\"$org_type\", org_id=\"$org_id\", user_name=\"$user_name\"}[$__range]))) / increase(http_request_duration_seconds_count{http_response_status_code!=\"\", http_route=~\"$route\", exported_job=\"$app\", org_type=\"$org_type\", org_id=\"$org_id\", user_name=\"$user_name\"}[$__range])",
     "legendFormat": "[{{http_response_status_code}}] {{http_route}}"
    }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "description": "Details of each API",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "topk(5, sum by(exported_job, http_method, http_route) (rate(http_request_duration_seconds_sum{exported_job=\"$app\", http_route=~\"$route\", org_type=\"$org_type\", org_id=\"$org_id\", user_name=\"$user_name\"}[$__range])) * 60) "
    },
    {
     "expr": "topk(5, histogram_quantile(0.95, sum by(le, exported_job, http_method, http_route) (rate(http_request_duration_seconds_bucket{exported_job=\"$app\", http_route=~\"$route\", org_type=\"$org_type\", org_id=\"$org_id\", user_name=\"$user_name\"}[$__range]))))"
    },
    {
     "expr": "sum by(exported_job, http_method, http_route) (rate(http_request_duration_seconds_count{exported_job=\"$app\", http_route=~\"$route\", http_status_code=~\"4.*|5.*\", org_type=\"$org_type\", org_id=\"$org_id\", user_name=\"$user_name\"}[$__range])) / topk(5, sum by(exported_job, http_method, http_route) (rate(http_request_duration_seconds_count{exported_job=\"$app\", http_route=~\"$route\", org_type=\"$org_type\", org_id=\"$org_id\", user_name=\"$user_name\"}[$__range])))"
    }
   ]
  }
 ]
}