apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
  namespace: logging
data:
  config.xml: |
    <clickhouse>
        <logger>
            <level>information</level>
            <console>true</console>
        </logger>
        <http_port>8123</http_port>
        <tcp_port>9000</tcp_port>
        <listen_host>0.0.0.0</listen_host>
        <max_connections>4096</max_connections>
        <keep_alive_timeout>10</keep_alive_timeout>
        <max_concurrent_queries>100</max_concurrent_queries>
        <uncompressed_cache_size>8589934592</uncompressed_cache_size>
        <mark_cache_size>5368709120</mark_cache_size>
        <path>/var/lib/clickhouse/</path>
        <tmp_path>/var/lib/clickhouse/tmp/</tmp_path>
        <user_files_path>/var/lib/clickhouse/user_files/</user_files_path>
        <users_config>users.xml</users_config>
        <default_profile>default</default_profile>
        <default_database>default</default_database>
        <timezone>UTC</timezone>
        <mlock_executable>false</mlock_executable>
        <merge_tree>
            <ttl_only_drop_parts>1</ttl_only_drop_parts>
            <merge_with_ttl_timeout>86400</merge_with_ttl_timeout>
        </merge_tree>
    </clickhouse>

  users.xml: |
    <clickhouse>
        <profiles>
            <default>
                <max_memory_usage>1500000000</max_memory_usage>
                <max_memory_usage_for_user>1700000000</max_memory_usage_for_user>
                <use_uncompressed_cache>1</use_uncompressed_cache>
                <load_balancing>random</load_balancing>
                <allow_experimental_object_type>1</allow_experimental_object_type>
                <max_bytes_before_external_sort>512000000</max_bytes_before_external_sort>
                <max_bytes_before_external_group_by>512000000</max_bytes_before_external_group_by>
                <max_rows_to_read>1000000</max_rows_to_read>
                <max_rows_to_group_by>100000</max_rows_to_group_by>
                <max_bytes_in_distinct>100000000</max_bytes_in_distinct>
                <max_rows_in_distinct>100000</max_rows_in_distinct>
                <max_rows_in_set>100000</max_rows_in_set>
                <max_bytes_in_set>100000000</max_bytes_in_set>
                <max_rows_in_join>100000</max_rows_in_join>
                <max_bytes_in_join>100000000</max_bytes_in_join>
            </default>
        </profiles>

        <users>
            <default>
                <password>clickhouse</password>
                <profile>default</profile>
                <networks>
                    <ip>::/0</ip>
                </networks>
                <quota>default</quota>
                <access_management>1</access_management>
            </default>
        </users>

        <quotas>
            <default>
                <interval>
                    <duration>3600</duration>
                    <queries>0</queries>
                    <errors>0</errors>
                    <result_rows>0</result_rows>
                    <read_rows>0</read_rows>
                    <execution_time>0</execution_time>
                </interval>
            </default>
        </quotas>
    </clickhouse>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:25.4
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8123
        - name: tcp
          containerPort: 9000
        volumeMounts:
        - name: clickhouse-config
          mountPath: /etc/clickhouse-server/config.d/
          readOnly: true
        - name: clickhouse-users
          mountPath: /etc/clickhouse-server/users.d/
          readOnly: true
        - name: clickhouse-data
          mountPath: /var/lib/clickhouse
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "500m"
          limits:
            memory: "2.5Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: clickhouse-config
        configMap:
          name: clickhouse-config
          items:
          - key: config.xml
            path: custom-config.xml
      - name: clickhouse-users
        configMap:
          name: clickhouse-config
          items:
          - key: users.xml
            path: custom-users.xml
      - name: clickhouse-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: logging
spec:
  ports:
  - port: 8123
    name: http
    targetPort: 8123
  - port: 9000
    name: tcp
    targetPort: 9000
  selector:
    app: clickhouse
