apiVersion: 1

groups:
  - name: serversage-alerts
    folder: ServerSage Alerts
    interval: 30s
    rules:
      - uid: error-rate-alert
        title: High Error Rate Alert
        condition: A
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasource:
              type: prometheus
              uid: prometheus
            model:
              expr: rate(serversage_http_requests_total{status=~"5.."}[5m]) > 0.1
              interval: ''
              refId: A
        noDataState: NoData
        execErrState: Alerting
        for: 1m
        annotations:
          description: 'Error rate is high'
          summary: 'ServerSage application error rate is high'
        labels:
          severity: warning
          team: backend
          service: serversage

      - uid: response-time-alert
        title: High Response Time Alert
        condition: A
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasource:
              type: prometheus
              uid: prometheus
            model:
              expr: histogram_quantile(0.95, rate(serversage_http_request_duration_seconds_bucket[5m])) * 1000 > 2000
              interval: ''
              refId: A
        noDataState: NoData
        execErrState: Alerting
        for: 2m
        annotations:
          description: '95th percentile response time is high'
          summary: 'ServerSage application response time is high'
        labels:
          severity: warning
          team: backend
          service: serversage
