{
 "title": "Slow Query",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds)"
   },
   {
    "name": "release",
    "label": "Release",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds{kubernetes_namespace=\"$namespace\"})"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result(pg_up{release=\"$release\"})"
   },
   { "name": "datname", "label": "Database", "query": "label_values(datname)" },
   {
    "name": "mode",
    "label": "Lock table",
    "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
   }
  ]
 },
 "panels": [
  { "title": "Settings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Query calls",
   "type": "timeseries",
   "description": "Number of times query called by user",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "pg_stat_statements_calls{instance=\"$instance\",rolname!=\"exp_pg\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query State count",
   "type": "gauge",
   "description": "Number of state of query from pg_stat_activity",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (state) (pg_active_slowqry_pid{instance=\"$instance\",rolname!=\"exp_pg\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recent slow queries",
   "type": "table",
   "description": "this data from pg_stat_activity",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": " (pg_active_slowqry_pid{instance=\"$instance\"})",
     "legendFormat": "queryid:{{queryid}}"
    }
   ]
  },
  {
   "title": "Top 10 queries by total execution time",
   "type": "timeseries",
   "description": "this data from pg_stat_statements",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10,  (pg_stat_statements_total_time_seconds{instance=\"$instance\",rolname!=\"exp_pg\"}))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}