receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 1024

  resource:
    attributes:
      - key: service.name
        value: serversage
        action: upsert
      - key: service.version
        value: 1.0.0
        action: upsert
      - key: deployment.environment
        value: development
        action: upsert

exporters:
  # Tempo for traces (gRPC endpoint)
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  # Prometheus for metrics with exemplars
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"
    add_metric_suffixes: false
    send_metadata: true
    resource_to_telemetry_conversion:
      enabled: true

  # Loki for logs with simplified configuration
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

  # Debug exporter for troubleshooting
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlp/tempo]

    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [prometheusremotewrite]

    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [loki]

  extensions: []
