
---
# ConfigMap for Elasticsearch configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: elastic
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |-
    cluster.name: es-cluster
    node.master: ${NODE_MASTER}
    node.data: ${NODE_DATA}
    node.ingest: ${NODE_INGEST}
    network.host: 0.0.0.0
    reindex.remote.whitelist: ["elasticsearch.e-search.svc.cluster.local:9200", "elasticsearch.e-search.svc.cluster.local"]
    discovery.seed_hosts: ["elasticsearch-master-0.elasticsearch-master.elastic.svc.cluster.local", "elasticsearch-master-1.elasticsearch-master.elastic.svc.cluster.local", "elasticsearch-master-2.elasticsearch-master.elastic.svc.cluster.local"]
    cluster.initial_master_nodes: ["elasticsearch-master-0", "elasticsearch-master-1", "elasticsearch-master-2"]
    bootstrap.memory_lock: true
    
    # Lower ping timeouts to detect node failures faster
    transport.ping_schedule: 5s
    
    # Enable automatic recovery and fault tolerance
    gateway.recover_after_nodes: 2
    gateway.expected_nodes: 3
    gateway.recover_after_time: 1m
    
    # Increase cluster stability
    cluster.routing.allocation.node_initial_primaries_recoveries: 4
    cluster.routing.allocation.node_concurrent_recoveries: 2
    
    xpack.security.enabled: false
    xpack.monitoring.collection.enabled: true
  jvm.options: |-
    -Xms1g
    -Xmx1g
    -XX:+UseConcMarkSweepGC
    -XX:CMSInitiatingOccupancyFraction=75
    -XX:+UseCMSInitiatingOccupancyOnly
    -XX:+AlwaysPreTouch
    -server
    -Djava.awt.headless=true
    -Dfile.encoding=UTF-8
    -Djna.nosys=true
    -XX:-OmitStackTraceInFastThrow
    -XX:+ShowCodeDetailsInExceptionMessages
    -Dio.netty.noUnsafe=true
    -Dio.netty.noKeySetOptimization=true
    -Dio.netty.recycler.maxCapacityPerThread=0
    -Dlog4j.shutdownHookEnabled=false
    -Dlog4j2.disable.jmx=true
    -Djava.io.tmpdir=${ES_TMPDIR}
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:HeapDumpPath=data
    -XX:ErrorFile=logs/hs_err_pid%p.log
    -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m

---
# Headless Service for StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elastic
  labels:
    app: elasticsearch
spec:
  clusterIP: None
  selector:
    app: elasticsearch
  ports:
  - port: 9200
    name: http
    protocol: TCP
  - port: 9300
    name: transport
    protocol: TCP

---
# Service for client nodes
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-client
  namespace: elastic
  labels:
    app: elasticsearch
    role: client
spec:
  type: ClusterIP
  selector:
    app: elasticsearch
    role: client
  ports:
  - port: 9200
    name: http
    targetPort: 9200
  - port: 9300
    name: transport
    targetPort: 9300

---
# Service for master nodes
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master
  namespace: elastic
  labels:
    app: elasticsearch
    role: master
spec:
  clusterIP: None
  selector:
    app: elasticsearch
    role: master
  ports:
  - port: 9300
    name: transport

---
# Service for data nodes
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data
  namespace: elastic
  labels:
    app: elasticsearch
    role: data
spec:
  clusterIP: None
  selector:
    app: elasticsearch
    role: data
  ports:
  - port: 9300
    name: transport

---
# Storage class for Elasticsearch
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: elastic
  name: elasticsearch-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

---
# PersistentVolumes for Master Nodes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-master-pv-0
  namespace: elastic
  labels:
    app: elasticsearch
    role: master
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: elasticsearch-storage
  hostPath:
    path: /data/elasticsearch/master-0
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-master-pv-1
  namespace: elastic
  labels:
    app: elasticsearch
    role: master
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: elasticsearch-storage
  hostPath:
    path: /data/elasticsearch/master-1
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-master-pv-2
  namespace: elastic
  labels:
    app: elasticsearch
    role: master
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: elasticsearch-storage
  hostPath:
    path: /data/elasticsearch/master-2
    type: DirectoryOrCreate

---
# PersistentVolumes for Data Nodes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data-pv-0
  namespace: elastic
  labels:
    app: elasticsearch
    role: data
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: elasticsearch-storage
  hostPath:
    path: /data/elasticsearch/data-0
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data-pv-1
  namespace: elastic
  labels:
    app: elasticsearch
    role: data
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: elasticsearch-storage
  hostPath:
    path: /data/elasticsearch/data-1
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data-pv-2
  namespace: elastic
  labels:
    app: elasticsearch
    role: data
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: elasticsearch-storage
  hostPath:
    path: /data/elasticsearch/data-2
    type: DirectoryOrCreate

---
# StatefulSet for Master Nodes
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-master
  namespace: elastic
  labels:
    app: elasticsearch
    role: master
spec:
  serviceName: elasticsearch-master
  replicas: 2
  selector:
    matchLabels:
      app: elasticsearch
      role: master
  template:
    metadata:
      labels:
        app: elasticsearch
        role: master
    spec:
      # affinity:
      #   podAntiAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 100
      #       podAffinityTerm:
      #         labelSelector:
      #           matchExpressions:
      #           - key: role
      #             operator: In
      #             values:
      #             - master
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - my-cluster-worker3
              topologyKey: kubernetes.io/hostname
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      - name: fix-permissions
        image: busybox:1.27.2
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: elasticsearch-master-data
          mountPath: /usr/share/elasticsearch/data
      containers:
      - name: elasticsearch-master
        image: bitnami/elasticsearch:8.11.1
        resources:
          limits:
            cpu: 800m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: cluster.name
          value: es-cluster
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "false"
        - name: NODE_INGEST
          value: "false"
        - name: bootstrap.memory_lock
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms1g -Xmx1g"
        - name: ES_TMPDIR
          value: /tmp
        volumeMounts:
        - name: elasticsearch-master-data
          mountPath: /usr/share/elasticsearch/data
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: config
          mountPath: /usr/share/elasticsearch/config/jvm.options
          subPath: jvm.options
        readinessProbe:
          exec:
            command:
            - bash
            - -c
            - |
              #!/usr/bin/env bash
              set -e
              curl --silent --fail localhost:9200/_cluster/health?wait_for_status=yellow
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      volumes:
      - name: config
        configMap:
          name: elasticsearch-config
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-master-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: elasticsearch-storage
      resources:
        requests:
          storage: 1Gi

---
# StatefulSet for Data Nodes
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-data
  namespace: elastic
  labels:
    app: elasticsearch
    role: data
spec:
  serviceName: elasticsearch-data
  replicas: 2
  selector:
    matchLabels:
      app: elasticsearch
      role: data
  template:
    metadata:
      labels:
        app: elasticsearch
        role: data
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: role
                  operator: In
                  values:
                  - data
              topologyKey: kubernetes.io/hostname
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      - name: fix-permissions
        image: busybox:1.27.2
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: elasticsearch-data-data
          mountPath: /usr/share/elasticsearch/data
      containers:
      - name: elasticsearch-data
        image: bitnami/elasticsearch:8.11.1
        resources:
          limits:
            cpu: 800m
            memory: 3Gi
          requests:
            cpu: 500m
            memory: 2Gi
        ports:
        - containerPort: 9300
          name: transport
        env:
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: cluster.name
          value: es-cluster
        - name: NODE_MASTER
          value: "false"
        - name: NODE_DATA
          value: "true"
        - name: NODE_INGEST
          value: "true"
        - name: bootstrap.memory_lock
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms2g -Xmx2g"
        - name: ES_TMPDIR
          value: /tmp
        - name: discovery.seed_hosts
          value: "elasticsearch-master-0.elasticsearch-master.elastic.svc.cluster.local,elasticsearch-master-1.elasticsearch-master.elastic.svc.cluster.local,elasticsearch-master-2.elasticsearch-master.elastic.svc.cluster.local"
        volumeMounts:
        - name: elasticsearch-data-data
          mountPath: /usr/share/elasticsearch/data
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: config
          mountPath: /usr/share/elasticsearch/config/jvm.options
          subPath: jvm.options
        readinessProbe:
          exec:
            command:
            - bash
            - -c
            - |
              #!/usr/bin/env bash
              set -e
              curl --silent --fail localhost:9200/_cluster/health?wait_for_status=yellow
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      volumes:
      - name: config
        configMap:
          name: elasticsearch-config
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-data-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: elasticsearch-storage
      resources:
        requests:
          storage: 2Gi

---
# Deployment for Client Nodes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-client
  namespace: elastic
  labels:
    app: elasticsearch
    role: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
      role: client
  template:
    metadata:
      labels:
        app: elasticsearch
        role: client
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: role
                  operator: In
                  values:
                  - client
              topologyKey: kubernetes.io/hostname
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch-client
        image: bitnami/elasticsearch:8.11.1
        resources:
          limits:
            cpu: 800m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: cluster.name
          value: es-cluster
        - name: NODE_MASTER
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: NODE_INGEST
          value: "true"
        - name: bootstrap.memory_lock
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms1g -Xmx1g"
        - name: ES_TMPDIR
          value: /tmp
        - name: discovery.seed_hosts
          value: "elasticsearch-master-0.elasticsearch-master.elastic.svc.cluster.local,elasticsearch-master-1.elasticsearch-master.elastic.svc.cluster.local,elasticsearch-master-2.elasticsearch-master.elastic.svc.cluster.local"
        volumeMounts:
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: config
          mountPath: /usr/share/elasticsearch/config/jvm.options
          subPath: jvm.options
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      volumes:
      - name: config
        configMap:
          name: elasticsearch-config