# Method 3: ServiceMonitor with ExternalName Service (for DNS-based discovery)

# ExternalName Service for App Zone Load Balancer
apiVersion: v1
kind: Service
metadata:
  name: app-zone-lb
  namespace: prometheus
  labels:
    app: app-zone-lb
    zone: app
spec:
  type: ExternalName
  externalName: app-zone-lb.company.local  # Your app zone load balancer DNS
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
    protocol: TCP

---
# ServiceMonitor for DNS-based discovery
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-zone-lb-discovery
  namespace: prometheus
  labels:
    app: app-zone-lb
    zone: app
spec:
  selector:
    matchLabels:
      app: app-zone-lb
      zone: app
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    honorLabels: true

---