# Method 1: ServiceMonitor with External Services (Headless Services pointing to external IPs)
---
# External Service for App Zone Exporters
apiVersion: v1
kind: Service
metadata:
  name: app-zone-node-exporter
  namespace: prometheus
  labels:
    app: app-zone-node-exporter
    zone: app
spec:
  type: ClusterIP
  clusterIP: None  # Headless service
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
    protocol: TCP

---
# Endpoints for External App Zone Node Exporters
apiVersion: v1
kind: Endpoints
metadata:
  name: app-zone-node-exporter
  namespace: prometheus
subsets:
- addresses:
  - ip: "192.168.2.10"  # App zone node 1
    nodeName: "app-node-1"
  - ip: "192.168.2.11"  # App zone node 2
    nodeName: "app-node-2"
  - ip: "192.168.2.12"  # App zone node 3
    nodeName: "app-node-3"
  ports:
  - name: metrics
    port: 9100
    protocol: TCP

---
# ServiceMonitor for App Zone Node Exporters
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-zone-node-exporter
  namespace: prometheus
  labels:
    app: app-zone-node-exporter
    zone: app
spec:
  selector:
    matchLabels:
      app: app-zone-node-exporter
      zone: app
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    honorLabels: true
    relabelings:
    - sourceLabels: [__address__]
      targetLabel: instance
    - sourceLabels: [__meta_kubernetes_endpoint_node_name]
      targetLabel: node
    - targetLabel: zone
      replacement: app-zone

---
# External Service for App Zone Applications
apiVersion: v1
kind: Service
metadata:
  name: app-zone-applications
  namespace: prometheus
  labels:
    app: app-zone-applications
    zone: app
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: otel-metrics
    port: 4317
    targetPort: 4317
    protocol: TCP

---
# Endpoints for App Zone Applications
apiVersion: v1
kind: Endpoints
metadata:
  name: app-zone-applications
  namespace: prometheus
subsets:
- addresses:
  - ip: "192.168.2.20"  # App 1
  - ip: "192.168.2.21"  # App 2
  - ip: "192.168.2.22"  # App 3
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
  - name: otel-metrics
    port: 4317
    protocol: TCP

---
# ServiceMonitor for App Zone Applications
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-zone-applications
  namespace: prometheus
  labels:
    app: app-zone-applications
    zone: app
spec:
  selector:
    matchLabels:
      app: app-zone-applications
      zone: app
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
    honorLabels: true
    relabelings:
    - sourceLabels: [__address__]
      targetLabel: instance
    - targetLabel: zone
      replacement: app-zone
    - targetLabel: service_type
      replacement: application
  - port: otel-metrics
    interval: 15s
    path: /metrics
    honorLabels: true
    relabelings:
    - sourceLabels: [__address__]
      targetLabel: instance
    - targetLabel: zone
      replacement: app-zone
    - targetLabel: service_type
      replacement: otel-collector

---