{
 "title": "Broadside Email Service",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datname", "label": "datname", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(bs_email_count_total,instance)"
    }
   },
   {
    "name": "app",
    "label": "Service",
    "query": {
     "query": "label_values(bs_email_count_total,app)"
    }
   },
   {
    "name": "dcs",
    "label": "Datacenter",
    "query": {
     "query": "label_values(bs_email_count_total,dcs)"
    }
   },
   {
    "name": "provider",
    "label": "Domain",
    "query": {
     "query": "label_values(bs_email_count_total,provider)"
    }
   },
   {
    "name": "state",
    "label": "Application ID",
    "query": {
     "query": "label_values(bs_email_count_total,state)"
    }
   },
   {
    "name": "status",
    "label": "Status",
    "query": {
     "query": "label_values(bs_email_count_total,status)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Email Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Datacenter Wise : (Domain : [[provider]], AppID : [[state]], Status : [[status]])",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count by (dcs)(bs_email_count_total{instance=~\"$instance\",dcs=~\"$dcs\",app=~\"$app\",provider=~\"$provider\",state=~\"$state\",status=~\"$status\"})",
     "legendFormat": "Datacenter: {{dcs}}"
    }
   ]
  },
  {
   "title": "Status Wise : (DC: [[dcs]], Domain : [[provider]], AppID : [[state]])",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diffperc" ] } },
   "targets": [
    {
     "expr": "count by (status)(bs_email_count_total{instance=~\"$instance\",dcs=~\"$dcs\",app=~\"$app\",provider=~\"$provider\",state=~\"$state\",status=~\"$status\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Domain Wise : (DC: [[dcs]], AppID : [[state]], Status : [[status]])",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diffperc" ] } },
   "targets": [
    {
     "expr": "count by (provider) (bs_email_count_total{instance=~\"$instance\",dcs=~\"$dcs\",app=~\"$app\",provider=~\"$provider\",state=~\"$state\",status=~\"$status\"})",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Application Wise : (DC: [[dcs]], Domain : [[provider]], Status : [[status]])",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (state)(bs_email_count_total{instance=~\"$instance\",dcs=~\"$dcs\",app=~\"$app\",provider=~\"$provider\",state=~\"$state\",status=~\"$status\"})",
     "legendFormat": "App Id: {{state}}"
    }
   ]
  }
 ]
}