{
 "title": "MinIO Dashboard",
 "description": "MinIO Grafana Dashboard - https://min.io/",
 "tags": [ "minio" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "scrape_jobs", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(minio_node_process_starttime_seconds{job=~\"$scrape_jobs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Online/Offline Drives",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_drive_online_total{job=~\"$scrape_jobs\"})",
     "legendFormat": "."
    },
    {
     "expr": "max(minio_cluster_drive_offline_total{job=~\"$scrape_jobs\"})",
     "legendFormat": "."
    }
   ]
  },
  {
   "title": "nodes online / offline",
   "type": "stat",
   "description": "Total number of MinIO nodes online",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "(minio_cluster_nodes_online_total{job=~\"$scrape_jobs\"} )",
     "legendFormat": "online"
    },
    {
     "expr": "(minio_cluster_nodes_offline_total{job=~\"$scrape_jobs\"} )",
     "legendFormat": "offline"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_total_bytes{job=~\"$scrape_jobs\"}) by (instance)) - topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=~\"$scrape_jobs\"}) by (instance))",
     "legendFormat": "Used"
    },
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=~\"$scrape_jobs\"}) by (instance)) ",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Is the webhook online?",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "(minio_cluster_webhook_online{job=~\"$scrape_jobs\"} )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time Since Last Scan",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(minio_usage_last_activity_nano_seconds{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Cluster Health Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_health_status{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool: {{pool}} Set: {{set}}"
    }
   ]
  },
  {
   "title": "Total Online Servers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_nodes_online_total{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Total S3 Egress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (minio_s3_traffic_sent_bytes{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Count of healing drives",
   "type": "stat",
   "description": "Get the count of healing drives of this erasure set",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(minio_cluster_health_erasure_set_healing_drives{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(minio_node_process_cpu_total_seconds{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Memory Usage ",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_node_process_resident_memory_bytes{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Number of Buckets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_bucket_total{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Total S3 Ingress",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (minio_s3_traffic_received_bytes{job=~\"$scrape_jobs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_usage_object_total{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  { "title": "details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Object Size Distribution",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_objects_size_distribution{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "S3 API Egress Rate ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (server) (rate(minio_s3_traffic_sent_bytes{job=~\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "Data Sent [{{server}}]"
    }
   ]
  },
  {
   "title": "S3 API Request Error Rate (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (server,api) (increase(minio_s3_requests_errors_total{job=~\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{server,api}}"
    }
   ]
  },
  {
   "title": "Health Breakdown",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_health_erasure_set_online_drives{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Online Drives"
    },
    {
     "expr": "minio_cluster_health_erasure_set_read_quorum{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Read Quorum"
    },
    {
     "expr": "minio_cluster_health_erasure_set_write_quorum{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Write Quorum"
    },
    {
     "expr": "minio_cluster_health_erasure_set_healing_drives{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Healing Drives"
    },
    {
     "expr": "minio_cluster_health_erasure_set_status{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Status"
    }
   ]
  },
  {
   "title": "Data Usage Growth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(minio_cluster_usage_total_bytes{job=~\"$scrape_jobs\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "minio_node_file_descriptor_open_total{job=~\"$scrape_jobs\"}",
     "legendFormat": "Open FDs [{{server}}]"
    }
   ]
  },
  {
   "title": "S3 API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (server,api) (increase(minio_s3_requests_incoming_total{job=~\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{server,api}}"
    }
   ]
  },
  {
   "title": "S3 API Ingress Rate ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 9, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (server) (rate(minio_s3_traffic_received_bytes{job=~\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "Data Received [{{server}}]"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 29 },
   "targets": [
    {
     "expr": "minio_node_go_routine_total{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "S3 API Request Error Rate (4xx)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (server,api) (increase(minio_s3_requests_rejected_invalid_total{job=~\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{server,api}}"
    }
   ]
  },
  {
   "title": "Open FDs ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 34 },
   "targets": [
    {
     "expr": "minio_node_file_descriptor_open_total{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Read, Write I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(minio_node_io_rchar_bytes{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Node RChar [{{server}}]"
    },
    {
     "expr": "rate(minio_node_io_wchar_bytes{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Node WChar [{{server}}]"
    }
   ]
  },
  {
   "title": "Scanned Objects",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(minio_node_scanner_objects_scanned{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "[{{server}}]"
    }
   ]
  },
  {
   "title": "Syscalls",
   "type": "timeseries",
   "description": "Number of online drives per MinIO Server",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(minio_node_syscall_read_total{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Read Syscalls [{{server}}]"
    },
    {
     "expr": "rate(minio_node_syscall_write_total{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Write Syscalls [{{server}}]"
    }
   ]
  },
  {
   "title": "Scanned Versions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(minio_node_scanner_versions_scanned{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "[{{server}}]"
    }
   ]
  },
  {
   "title": "s3 Traffic",
   "type": "timeseries",
   "description": "Total number of s3 bytes received and sent on MinIO cluster",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(minio_s3_traffic_sent_bytes{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Internode Bytes Received [{{server}}]"
    },
    {
     "expr": "rate(minio_s3_traffic_received_bytes{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Internode Bytes Sent [{{server}}]"
    }
   ]
  },
  {
   "title": "Scanned Directories",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(minio_node_scanner_directories_scanned{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "[{{server}}]"
    }
   ]
  },
  {
   "title": "Bucket Scans Started",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(minio_node_scanner_bucket_scans_started{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "[{{server}}]"
    }
   ]
  },
  {
   "title": "Bucket Scans Finished",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(minio_node_scanner_bucket_scans_finished{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "[{{server}}]"
    }
   ]
  }
 ]
}