apiVersion: v1
kind: PersistentVolume
metadata:
  name: rancher-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /kind-data/rancher-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rancher-pvc
  namespace: cattle-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---