---
apiVersion: v1
kind: Secret
metadata:
  name: rancher-secret
  namespace: cattle-system
type: Opaque
stringData:
  password: admin123  # Change this
---
apiVersion: v1
kind: Service
metadata:
  name: rancher-service
  namespace: cattle-system
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      nodePort: 30015
      name: https
  selector:
    app: rancher
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher
  namespace: cattle-system
  labels:
    app: rancher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher
  template:
    metadata:
      labels:
        app: rancher
    spec:
      serviceAccountName: rancher-serviceaccount
      containers:
        - name: rancher
          image: rancher/rancher:v2.11.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - mountPath: /var/lib/rancher
              name: rancher-data
          env:
            - name: CATTLE_BOOTSTRAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rancher-secret
                  key: password
      volumes:
        - name: rancher-data
          persistentVolumeClaim:
            claimName: rancher-pvc

---

