apiVersion: v1
kind: Pod
metadata:
  name: elastic-exporter
  namespace: exporters
  labels:
    app: elastic-exporter
spec:
  nodeName: aws-worker-1
  containers:
  - name: elastic-exporter
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    args:
      - --es.uri=http://elasticsearch.database.svc.cluster.local:9200
      - --es.all
      - --es.indices
    ports:
      - containerPort: 9114
        protocol: TCP
    volumeMounts:
      - name: kube-api-access
        mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        readOnly: true
  volumes:
    - name: kube-api-access
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    fieldPath: metadata.namespace
  restartPolicy: Always
  serviceAccountName: default
  dnsPolicy: ClusterFirst