# Storage Classes
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prometheus-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

---
# PersistentVolume for Thanos Store Gateway
apiVersion: v1
kind: PersistentVolume
metadata:
  name: thanos-store-gateway-data
  labels:
    app: thanos-store-gateway
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /bse-data/data/monitoring/prometheus-ha/thanos-store
    type: DirectoryOrCreate

---
# PersistentVolumeClaim for Thanos Store Gateway
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thanos-store-gateway-data
  namespace: monitoring
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# PersistentVolume for Prometheus instance 0
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-prometheus-db-prometheus-0
  labels:
    app: prometheus
    prometheus: prometheus
    prometheus-instance: "0"
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: prometheus-storage
  hostPath:
    path: /bse-data/data/monitoring/prometheus-ha/prometheus-0
    type: DirectoryOrCreate

---
# PersistentVolume for Prometheus instance 1
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-prometheus-db-prometheus-1
  labels:
    app: prometheus
    prometheus: prometheus
    prometheus-instance: "1"
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: prometheus-storage
  hostPath:
    path: /bse-data/data/monitoring/prometheus-ha/prometheus-1
    type: DirectoryOrCreate

---
# Note: PVCs for Prometheus will be automatically created by Prometheus Operator
# with names: prometheus-prometheus-db-prometheus-0 and prometheus-prometheus-db-prometheus-1
# If you need to pre-create them manually, uncomment below:

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: prometheus-prometheus-db-prometheus-0
#   namespace: monitoring
#   labels:
#     app: prometheus
# spec:
#   storageClassName: prometheus-storage
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: prometheus-prometheus-db-prometheus-1
#   namespace: monitoring
#   labels:
#     app: prometheus
# spec:
#   storageClassName: prometheus-storage
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi