apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: logharbour # Ensure this matches your Kafka namespace
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest # Use the latest or a specific version
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "My Kafka Cluster" # You can change this name
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka.logharbour.svc.cluster.local:9092" # Use your Kafka service name and port.  Adjust the namespace if needed.
          livenessProbe:
            httpGet: # Changed from http to httpGet
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet: # Changed from http to httpGet
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
  namespace: logharbour # Ensure this matches your Kafka namespace
  labels:
    app: kafka-ui
spec:
  selector:
    app: kafka-ui
  type: NodePort # Use ClusterIP for internal access within the cluster
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30014
