---
# ServiceMonitor for Node Exporter
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: node-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter
  endpoints:
  - port: metrics
    interval: 30s
    scrapeTimeout: 10s
---
# Service Monitor for Prometheus itself
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: monitoring
spec:
  selector:
    matchLabels:
      operated-prometheus: "true"
  endpoints:
  - port: web
---
# minio service monitor BSE
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio-metrics
  namespace: monitoring
  labels:
    app: minio-svm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  namespaceSelector:
    matchNames:
      - database
  endpoints:
    - port: http
      path: /minio/v2/metrics/cluster
      interval: 30s
      scheme: http
---
# ServiceMonitor for Kube State Metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/name: kube-state-metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
  - port: http-metrics
    interval: 30s
    scrapeTimeout: 30s
  - port: telemetry
    interval: 30s
    scrapeTimeout: 30s
---
# Redis-exporter Metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/name: redis-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
  - port: http
    interval: 30s
    scrapeTimeout: 30s
---
# otel-collector Metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/name: otel-collector
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
  - port: app-metrics
    interval: 30s
    scrapeTimeout: 30s
---
# postgres-exporter Metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/name: postgres-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
  - port: http
    interval: 30s
    scrapeTimeout: 30s
---
# kafka-exporter Metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-exporter-metrics
  namespace: monitoring
  labels:
    app: kafka-exporter
spec:
  selector:
    matchLabels:
      app: kafka-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
  - port: http
    interval: 30s
    scrapeTimeout: 30s
---
#  elastic-exporter Metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name:  elastic-exporter-metrics
  namespace: monitoring
  labels:
    app: elastic-exporter
spec:
  selector:
    matchLabels:
      app: elastic-exporter
  namespaceSelector:
    matchNames:
      - e-search
  endpoints:
  - port: metrics
    interval: 30s
    scrapeTimeout: 30s
---
# keycloak metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keycloak-metrics
  namespace: monitoring
  labels:
    app: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  namespaceSelector:
    matchNames:
      - starmfv2-qa
  endpoints:
    - port: metrics
      relabelings:
        - sourceLabels: [_address_]
          targetLabel: _address_
          regex: (.+)(?::\d+)
          replacement: $1:8088
          action: replace
      interval: 15s
      path: /metrics
---
# etcd metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: etcd-metrics
  namespace: monitoring
  labels:
    app: etcd
spec:
  selector:
    matchLabels:
      app: etcd
  namespaceSelector:
    matchNames:
      - starmfv2-qa
  endpoints:
    - port: http
      interval: 30s
      scheme: http