{
 "title": "Slow queries - V1.0",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds)"
   },
   {
    "name": "release",
    "label": "Release",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds{kubernetes_namespace=\"$namespace\"})"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result(pg_up{release=\"$release\"})"
   },
   { "name": "datname", "label": "Database", "query": "label_values(datname)" },
   {
    "name": "mode",
    "label": "Lock table",
    "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
   }
  ]
 },
 "panels": [
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Users",
   "type": "bargauge",
   "description": "This system view provides information about current database activity, including user names and query execution details. ",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (rolname) ((pg_stat_activity_count{instance=\"$instance\",datname=~\"$datname\"}))",
     "legendFormat": "{{rolname}}"
    }
   ]
  },
  {
   "title": "Total Connections By state",
   "type": "bargauge",
   "description": "from table pg_stat_activity",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (state) ((pg_stat_activity_count{instance=\"$instance\",datname=~\"$datname\"}))",
     "legendFormat": "{{rolname}}"
    }
   ]
  },
  {
   "title": "Total Active Connections on databases",
   "type": "gauge",
   "description": "Displays the total number of active connections to your PostgreSQL databases.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"active\",instance=\"$instance\"}) by (datname) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Backends Connections",
   "type": "gauge",
   "description": "Shows the number of backend processes currently connected to each database. This includes all states (active, idle, idle in transaction, etc.).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(pg_stat_database_numbackends{instance=\"$instance\"}) > 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Total Active Connections on databases",
   "type": "timeseries",
   "description": "Displays the total number of active connections to your PostgreSQL databases.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"active\",instance=\"$instance\"}) by (datname)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Backends Connections",
   "type": "timeseries",
   "description": "Shows the number of backend processes currently connected to each database. This includes all states (active, idle, idle in transaction, etc.).",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "(pg_stat_database_numbackends{instance=\"$instance\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Longest Running Transaction Duration",
   "type": "timeseries",
   "description": "Displays the duration of the longest running active transaction, useful for identifying potential bottlenecks. Number of backends currently connected to this database. This is the only column in this view that returns a value reflecting current state; all other columns return the accumulated values since the last reset.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max(pg_stat_database_numbackends{instance=\"$instance\"}) by (datname)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "pg state statements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 }, "repeat": "interval" },
  {
   "title": "Excessive Queries by Database",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (datname) (pg_stat_statements_calls{instance=\"$instance\",datname=~\"$datname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total active users / time frame",
   "type": "timeseries",
   "description": "This system view provides information about current database activity, including user names and query execution details. ",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 40 },
   "targets": [
    {
     "expr": "sum by (usename) ((pg_stat_activity_count{instance=\"$instance\",datname=~\"$datname\"}))",
     "legendFormat": "{{usename}}"
    }
   ]
  },
  {
   "title": "Last 100 executed queries",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "pg_stat_statements_calls{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pg_stat_statements_total_time_seconds{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Settings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Rate of Query calls by 5m",
   "type": "timeseries",
   "description": "Number of times query called by user",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "rate(pg_stat_statements_calls{instance=\"$instance\", rolname!=\"postgres_exporter\"}[5m])",
     "legendFormat": "USER: {{rolname}}, DB: {{datname}}, QRY:  {{query}}"
    }
   ]
  },
  {
   "title": "Top 10 Queries by Total Execution Time",
   "type": "timeseries",
   "description": "Displays the top 10 queries with the highest total execution time across the selected instance and database. This helps identify performance bottlenecks in your PostgreSQL queries.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(topk(10, pg_stat_statements_total_time_seconds{instance=\"$instance\", datname=~\"$datname\",rolname!=\"postgres\"}))",
     "legendFormat": "USER: {{rolname}}, DB: {{datname}}, QRY:  {{query}}"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Replication Lag (Seconds)",
   "type": "timeseries",
   "description": "Measures the time delay, in seconds, between the primary and replica servers. This is a critical metric for replication health.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "(pg_replication_lag_seconds{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Active Replication Slots",
   "type": "stat",
   "description": "This helps ensure that your replication slots are active and haven't failed.",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  sum(pg_replication_slots_active{instance=\"$instance\"}) by (slot_type)",
     "legendFormat": "{{database}} : {{slot_name}}"
    }
   ]
  },
  {
   "title": "Max Logical Replication Workers",
   "type": "stat",
   "description": "Shows the configured max_logical_replication_workers setting.",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  (pg_settings_max_logical_replication_workers{instance=\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replication Slot Current WAL LSN (logical)",
   "type": "timeseries",
   "description": "Tracks the current WAL LSN for each replication slot. Useful for observing the progress, especially for logical slots.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "targets": [
    {
     "expr": "(pg_replication_slot_slot_current_wal_lsn{instance=\"$instance\"})",
     "legendFormat": "{{slot_name}} : {{slot_type}}"
    }
   ]
  },
  {
   "title": "Replication Slot Lag (Bytes)",
   "type": "timeseries",
   "description": "Shows the difference in Write-Ahead Log (WAL) Sequence Numbers (LSN) for replication slots, indicating lag in bytes per slot.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "(pg_replication_slots_pg_wal_lsn_diff{instance=\"$instance\"})",
     "legendFormat": "{{slot_name}}"
    }
   ]
  },
  {
   "title": "Max transaction duration",
   "type": "timeseries",
   "description": "max duration in seconds any active transaction has been running",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(pg_stat_activity_max_tx_duration{instance=\"$instance\", datname=~\"$datname\",state=~\"active|idle*\"}) ",
     "legendFormat": "{{state}} : {{application_name}} : {{backend_type}} : {{datname}} : {{usename}} : {{wait_event}} : {{wait_event_type}}"
    }
   ]
  }
 ]
}